{
  "name": "grabx-api",
  "main": "src/index.ts",
  "compatibility_date": "2026-09-27",

{
  // ...
  "vars": {
    "API_BASE_URL": "https://nearby-sherline-mehermankarofficial-3b587d66.koyeb.app",
    "API_KEY": "meher"
  },

}
}